name: CI

on:
  push:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:

    - name: Checkout scm
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm

    - name: Run test
      run: |
        ./ci_scilla_type_check.sh && npm i && npm test
